# ---- Pipeline configuration ----

# -- Resource configuration --

# Maximum number of threads to use
nthreads: 16

# -- Pipeline configuration --

# What should your analysis be called? This is prepended to all
#   files written to disk from the pipline.
analysis_name: fletcher_LMS

# Where does the raw data live? This can be absolute or
#   relative to the directory where you Snakefile is
rawdata_dir: rawdata

# Where does the metadata live?
metadata_dir: metadata

# Where should processed data be written?
procdata_dir: procdata

# Where should the final results be written?
results_dir: results

# What type of array data?
# Options are: cytoscan, oncoscan or snp6
array_family: cytoscan

# Name of the pairs file for the .CEL files, just the name, path will be
#   built using the metadata_dir.
# See https://github.com/gustaveroussy/EaCoN for information
#   on the formatting the file for different array_families
pairs_file: 'fletcher_LMS_pairs.tsv'