# ---- Pipeline configuration ----

# -- Resource configuration --

# Maximum number of threads to use
nthreads: 16

# -- Pipeline configuration --

# What should your analysis be called? This is prepended to all
#   files written to disk from the pipline.
analysis_name: fletcher_LMS

# Where does the raw data live? This can be absolute or
#   relative to the directory where you Snakefile is
rawdata_dir: rawdata

# Where does the metadata live?
metadata_dir: metadata

# Where should processed data be written?
procdata_dir: procdata

# Where should the final results be written?
results_dir: results

# What type of array data?
# Options are: CytoscanHD, CytoScan750k, Oncoscan... 
array_type: CytoScanHD

# -- Preprocessing configuration --

# Which reference should be used?
# Options are from BSgenome: 
#   - for Cytoscan arrays: BSgenome.Hsapiens.UCSC.hg19 or 
#     BSgenome.Hsapiens.UCSC.hg38
#   - for other arrays please see https://github.com/gustaveroussy/EaCoN
reference: BSgenome.Hsapiens.UCSC.hg19

# Name of the pairs file for the .CEL files, just the name, path will be
#   built using the metadata_dir.
# See https://github.com/gustaveroussy/EaCoN for information
#   on the formatting the file for different array_families
pairs_file: 'fletcher_LMS_pairs.tsv'

# -- Segmentation configuration --

# Which segmenter should be used?
# Options are: ASCAT, FACETS or SEQUENZA
segmenter: 'ASCAT'

# Should data smoothing be performed during segmentation; good for noisy data.
# An integer value indicating the half-window size for winsorization. 
# Larger equals more smoothing, starting around 5 is recommended.
smoothk: 100

# --- Copy number estimation parameters

# The range of gamma values to consider when modelling allele specific copy number
# 
gamma_range: [0.35, 0.95]